// <autogenerated>

//------------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//------------------------------------------------------------------------------

using System;
using Microsoft.AppMagic.Transport;

namespace Microsoft.AppMagic.Authoring
{
    [TransportType(TransportKind.Enum)]
    public enum ServiceKind
    {
        CustomWadl = 3,
        ConnectedWadl = 4,
        AddinWadl = 5,
        HostWadl = 6,
        /// <summary>
        /// Service that infers its connection information (e.g. auth) from its corresponding dataset or datasource.
        /// </summary>
        DataBound = 7
    }

    [TransportType(TransportKind.ServerRemoted)]
    [TransportUnion(typeof(IAddinService), typeof(IService))]
    public interface IService
    {
        string ApiId { get; }

        /// <summary>The service namespace.</summary>
        string ServiceNamespace { get; }

        /// <summary>The kind of service this instance represents.</summary>
        ServiceKind Kind { get; }

        /// <summary>Specifies whether there are errors for the service</summary>
        bool HasErrors { get; }

        /// <summary>
        /// Specifies whether the service is used in any rules in the document.
        /// </summary>
        [TransportDisabled]
        bool IsInUse { get; }

        /// <summary>The runtime definition for this entity as stringified JSON.</summary>
        string RuntimeDefinitionJson { get; }
    }

    [TransportType(TransportKind.ServerRemoted)]
    public interface IAddinService : IService
    {
        /// <summary>The id of the Addin that owns this service.</summary>
        Guid AddinId { get; }

        /// <summary>The Addin-specific id for this service.</summary>
        Guid AddinConnectorId { get; }
    }
}
