// <autogenerated>
// Use autogenerated to suppress styelcop warnings since this is shared from another repo.

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

using Microsoft.PowerFx.Core.Types;
using Contracts = Microsoft.PowerFx.Core.Utils.Contracts;

namespace Microsoft.AppMagic.Authoring
{
    internal sealed class ServiceFunctionParameterTemplate
    {
        private readonly string _docRefId;
        private readonly TypedName _typedName;
        private readonly string _description;
        private readonly string _defaultValue;

        public string DocRefId { get { return _docRefId; } }

        public TypedName TypedName { get { return _typedName; } }

        public string Description { get { return _description; } }

        public string DefaultValue { get { return _defaultValue; } }

        public ServiceFunctionParameterTemplate(TypedName typedName, string description, string defaultValue, string docRefId)
        {
            Contracts.Assert(typedName.IsValid);
            Contracts.AssertValueOrNull(description);
            Contracts.AssertValueOrNull(defaultValue);
            // If docRefId is null, this means no documentation is provided for this element.
            Contracts.AssertNonEmptyOrNull(docRefId);

            _typedName = typedName;
            _description = description;
            _defaultValue = defaultValue;
            _docRefId = docRefId;
        }

        public ServiceFunctionParameterTemplate(TypedName typedName, string description, string defaultValue)
        {
            Contracts.Assert(typedName.IsValid);
            Contracts.AssertValueOrNull(description);
            Contracts.AssertValueOrNull(defaultValue);

            _typedName = typedName;
            _description = description;
            _defaultValue = defaultValue;
        }

    }
}
