// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

using Microsoft.PowerFx.Core.Localization;
using Microsoft.PowerFx.Syntax;
using Microsoft.PowerFx.Types;

namespace Microsoft.PowerFx.Core.IR
{
    [ThreadSafeImmutable]
    internal class IRContext
    {
        // This field may be null, for example when nodes are generated by the compiler
        // and do not correlate with a source location
        public Span SourceContext { get; }

        public FormulaType ResultType { get; }

        // We are in a mutation context, for example the first argument to Patch
        // Where needed, copies of the argument may need to be made for copy-on-write semantics
        public bool IsMutation { get; }

        internal IRContext(Span sourceContext, FormulaType resultType, bool isMutation = false)
        {
            SourceContext = sourceContext;
            ResultType = resultType;
            IsMutation = isMutation;
        }

        public static IRContext NotInSource(FormulaType resultType, bool isMutation = false)
        {
            return new IRContext(null, resultType, isMutation);
        }
    }
}
